### ISSUE TITLE
astra.isFrameNew() never true

### ISSUE THREAD

**Issue by antimodular** [mattfelsen/ofxOrbbecAstra#2]
hi
your addon looks promising.

i tried it on OS X 10.9 with xcode 6.4 and OF 0.9.0

the astra's laser seems to be turned on but no images are shown in the app.
astra.isFrameNew() always returns 0.

here the console print out:
https://gist.github.com/antimodular/c79d4dc73bd24702ae9d

any ideas?
thx

**Comment by antimodular** [comment]
also astra::Astra::initialize(); returns false at setup

**Comment by mattfelsen** [comment]
Interesting...I think this was working for me the last time I tried, though I don't have access to a cam currently so I can't verify.

Which type of camera are you using? Is it the Astra Pro? Notably there's an issue where the color stream isn't accessible via the Astra SDK and it causes other streams to fail as well if started. Does the example work if you only enable the depth and point streams, but not color? Have you tried the Astra SDK samples?

**Comment by antimodular** [comment]
thanks for the fast response.

commenting out astra.initColorStream(); did make the depth image work. thanks.

i am noticing horizontal bands of noise in the depth stream. i think i read about this problem before somewhere

**Comment by mattfelsen** [comment]
Cool, glad to know that was the problem. Check this forum thread for more related info:
https://3dclub.orbbec3d.com/t/color-image-not-firing-on-frame-event/192

Not sure about the horizontal bands, but guessing it's more of a sensor/SDK thing rather than something with this addon. Feel free to open another issue for that if you find out more. Thanks for checking this out!
