### ISSUE TITLE
Multiple Astra Sensor

### ISSUE THREAD

**Issue by I33N** [mattfelsen/ofxOrbbecAstra#4]
Hello,
Does your addon is supposed to support multiple sensors?
If I try to open 2 streams I get the same depth/color.
Is it even supported by the SDK?
Thanks,
Ben

**Comment by mattfelsen** [comment]
Hey Ben. There's a sample in the Astra SDK for multiple sensors, though it's in their develop branch so I'm not sure if the latests release (0.4) supports it. The way to address different sensors is to pass a string when creating the streamset:
https://github.com/orbbec/astra/blob/develop/samples/sfml/MultiSensorViewer-SFML/main.cpp#L417-L418

I've been meaning to add support to this addon since it should be simple, but haven't been able to test it since I don't have access to multiple cams. All you'd have to do is pass through a string to `ofxOrbbecAstra::setup` and then use that when creating the streamset:
https://github.com/mattfelsen/ofxOrbbecAstra/blob/master/src/ofxOrbbecAstra.cpp#L38

Let me know if that helps, and if it works! Happy to take at PR if you put one together :smile:

**Comment by I33N** [comment]
Indeed it works well with 2 sensors! Thank you!
I will make a PR shortly.

**Comment by mattfelsen** [comment]
Closed by #7
